spring:
  application:
    name: Frankit
  config:
    import:
      - config/application-database.yml
      - config/application-security.yml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  enable-spring-security: true